lib/volders_contract_manager_web/router.ex
defmodule VoldersContractManagerWeb.Router do
  use VoldersContractManagerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug Plug.Session, store: :cookie,
                  key: "_vcontractmanager",
                  encryption_salt: "supersecretsalt",
                  signing_salt: "supersecretsigningsalt",
                  key_length: 64,
                  log: :debug
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug Guardian.Plug.Pipeline, [module: VoldersContractManagerWeb.Guardian,
                                 error_handler: VoldersContractManagerWeb.AuthErrorHandler]
                                 
    plug Guardian.Plug.VerifyHeader, claims: %{"typ" => "access"}
    plug Guardian.Plug.VerifySession, claims: %{"typ" => "access"}
    plug Guardian.Plug.EnsureAuthenticated, claims: %{"typ" => "access"}
    plug Guardian.Plug.LoadResource, claims: %{"typ" => "access"}
  end

  scope "/", VoldersContractManagerWeb do
    pipe_through :browser

    get "/", Redirect, to: "/manager/contracts"

    get "/sign-up", UserController, :new
    get "/sign-in", UserController, :signin
    get "/sign-out", UserController, :signout
    post "/login", UserController, :login
    
    resources "/users", UserController, only: [:create]
  end

  scope "/manager", VoldersContractManagerWeb do
    pipe_through :browser
    pipe_through :auth

    resources "/vendors", VendorController
    resources "/categories", CategoryController
    resources "/contracts", ContractController
  end

  scope "/api", VoldersContractManagerWeb do
    pipe_through :api
    pipe_through :auth

    resources "/vendors", VendorController, only: [] do
      resources "/categories", Vendor.VendorCategoryController, only: [:index]
    end
  end
end

lib/volders_contract_manager_web/views/layout_view.ex
defmodule VoldersContractManagerWeb.LayoutView do
  use VoldersContractManagerWeb, :view
end

lib/volders_contract_manager_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello VoldersContractManager!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script>
      window._apiKey = "<%= VoldersContractManagerWeb.Guardian.Plug.current_token(@conn) %>";
    </script>
  </head>

  <body>
    <div class="container">
      <header class="header">
        <h1>
          <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
          <span class="app-name">
            <%= link "Contract Manager", to: contract_path(@conn, :index), class: "no-link" %>
          </span>

          <%= if VoldersContractManagerWeb.Guardian.user_signed_in?(@conn) do %>
          <div class="btn-group pull-right">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Contracts <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><%= link "List contracts", to: contract_path(@conn, :index) %></li>
              <li><%= link "Add new contract", to: contract_path(@conn, :new) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link "Sign out", to: user_path(@conn, :signout) %></li>
            </ul>
          </div>
          <% end %>
        </h1>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
  </body>
</html>